### PR TITLE
Add Tooltips to Showcase Website

### PR DESCRIPTION
**Pull request by aashishnagpal**

### CODE REVIEW

**Comment by jmatembu** [comment]
Hey @aashishnagpal,

I love these tooltips. One thing though:

* Shouldn't the last tooltip contain some HTML (including images) as it states?

**Comment by aashishnagpal** [comment]
Okay Joseph. Let me see if I can include an image there. 

I don't see it as an issue, if you compare it with Bootstrap's demo on their website, but still, I will try and find a random image to add it to the tooltip.

Thanks for not merging this one. I think I can just add the commit to this very PR.

**Comment by jmatembu** [comment]
> I don't see it as an issue

Neither do I. I have updated my earlier comment above.

I was just thinking if we state that **your tooltip can contain HTML including images**, a small image would be a **nice-to-have** demo. 😄

**Comment by aashishnagpal** [comment]
How about this image?
smilies

**Comment by aashishnagpal** [comment]
Hi @jmatembu 

I rebased with upstream development branch and thus you see there are so many commits. I had to merge and then resolve merge conflict too. Sorry about that.

**Comment by jmatembu** [comment]
No worries @aashishnagpal,

I like the image. Thanks for the update.

**Pull request merged**
