### PR TITLE
Add single-input form and space-saving-minimalist form to showcase page

### PR DESCRIPTION
**Pull request by Jing-Ran**

### CODE REVIEW

**Comment by brianhernandez** [comment]
Hey @Jing-Ran , I was actually working on adding your single input forms to the site the same time as you were.  I merged your changes into my local development branch and I also added the description of your component to the showcase site from your readme.me files.  After that I pushed the changes up to the development branch on GitHub.  When you get a chance, have a look at these changes and tell me what you think.  I can merge this whenever you are ready.

**Comment by Jing-Ran** [comment]
@brianhernandez Sorry that I interrupted your progress. I thought we should add components ourselves. Regarding the changes, thank you for making them. These are good. At first I thought the description there should be as brief as possible. And the full description would go to other places on the site. 

One thing, could you please help me delete the `|` right after the description from the single input form and space saving form? 

```
title: "Burst"
description: |
```

Joseph told me in another pull request that there shouldn't be a `|`. I copied/pasted from the instruction, so it exists in every file of mine.

**Comment by brianhernandez** [comment]
@Jing-Ran Oh no, no worries.  It's great you were adding your own components to the site.  We need the help so thanks a lot!  Yea, I'm not sure about the descriptions then.  Well, we can always change it to be shorter if it needs to be.  And we always have the `readme` if we need that again too.  Ok, I will merge this and make sure the pipes are gone in `description` in your jekyll files.

**Comment by Jing-Ran** [comment]
@brianhernandez I can finally see the showcase page on my side. I found out some issues on my side and not sure if they happen to you as well. These problems don't happen before adding to the showcase page.

1. Both of the forms sit on top of the markup section. I don't see other components have this problem. 
2. I can't type anything in both forms. 

I was trying to solve these problems before I saw your message. I'm gonna postpone what I'm doing now. Please let me know how they work on your side. 

If they work fine, I'll make a new pull request later to update some styles of the single input form.

**Comment by brianhernandez** [comment]
@Jing-Ran Yes, we seem them too.  For the number 2 we think there are other components that are having JavaScript errors that are interfering with your component.  If you open up Developer Tools you maybe can see some errors in JavaScript with other components.  For number 1, yea not too many other components are having this issue but I know Cubby and Herald seem to have it.  The Show Markup Button is not respective the space of the component.  I believe it is because these components have some elements that are positioned `absolute` could be part of the problem.   If you want you can try to see if you can fix it but I am thinking we should try to have some way for the Show Markup bar to clear these types of components.  

I have removed all the pipes and I am not working on your files now so if you want to change some things and do another pull request again that is fine.

**Comment by Jing-Ran** [comment]
@brianhernandez Thanks for the feedback. I'll update the styles of single input form and do a PR in about half an hour. 

For issue 1, my forms both have `position: relative` in the `<form>` tag because I need to absolutely position elements inside of them. I solved this positioning issue by giving the `div.site-markup` a top margin in my DevTools. 
screen shot 2017-04-07 at 2 34 15 pm

I keep the original position settings of my forms there. And see if the positioning issue can be solved after you guys work on the Show Markup bar a little bit. Please let me know if there is any issue.

**Comment by Jing-Ran** [comment]
Hi @brianhernandez, I checked out the gh page of the framework. It looks great. 

I found out some issues with the two forms I built and I think I should let you know. 

On the showcase page, the go next button of the single input form doesn't work. And for the minimalist form, an extra indicator appears on the right side of the form after clicking the go next button. 

I checked the console panel in DevTool, but didn't find any useful info. Also, both forms work correctly in their own folders. So I haven't made any change on my side. I understand your team is still working the showcase page, so I'll wait for further instructions. 

This is only a friendly reminder just in case you missed the issues. If there is anything I can fix on my side, please don't hesitate to let me know. Thanks.

**Comment by brianhernandez** [comment]
Hey @Jing-Ran.  Yes, I did notice at least the issue with the single input form not revealing the next input field.  At this point since there doesn't seem to be any JS issues on the showcase site now, I would suggest seeing what you can do with your own code by testing different things directly on the showcase site to resolve these issues.  I know I had to change the JavaScript of one of my components when it was on the showcase site because for some reason it operated a little differently than when it was in its own development folder.  Maybe because there are a lot of other JavaScript functions running from other components on the page.  Sorry I can't be more helpful than this at this point.

**Comment by Jing-Ran** [comment]
@brianhernandez Thank you for your feedback. You have been really helpful. I'll work on them and get back to you soon.

**Comment by Jing-Ran** [comment]
@brianhernandez 

I'm working on the single input form. I'm having trouble with using keyframes animations in my code. When I clicked the go next button, the next input field did show but without any animation. So I tracked down to the main.css file and couldn't find any of my @keyframes animations there. It seems like all my aniamtions are missing from this file but other css rules are added and compiled correctly. Could you please shed some light?

Thank you.

**Pull request merged**
