### PR TITLE
Add Drop Dot component

### PR DESCRIPTION
**Pull request by PatrickFranz**
Ready for review

### CODE REVIEW

**Comment by jmatembu** [comment]
@PatrickFranz 

I can only see the Drop Dot component on the showcase website. It is, however, neither listed in the `evolution` nor `standard` sub-folders (`assets/html/evolution|standard`). 

Please fix the following on the component:
* Change the link text color, perhaps to something close to `white`.
* Broken image (`profile.jpg`).

On the showcase, you will also need to add the author and category properties to your showcase file (`_components/dropdot.html`). Author, that's your name. Category, that's either `standard` or `evolution`. We will be adding this information to the contribution guide soon.

**Comment by PatrickFranz** [comment]
@jmatembu  My image appears to have been deleted. 
1. Where are images supposed to be located??
2. What is supposed to go in the html evolution directory? Obviously some HTML for my component, but maybe why is a better question?

**Comment by jmatembu** [comment]
@PatrickFranz 

> Where are images supposed to be located??

All component images are stored in `assets/images/components/name_of_component/`. When transferring your component to the showcase, you only need to update the paths to the images from something like `../../images/components/name_of_component/filename.jpg` to something like `../assets/images/components/name_of_component/filename.jpg`

> What is supposed to go in the html evolution directory? Obviously some HTML for my component, but maybe why is a better question?

We keep the innovative and standard components in their separate folders. All innovative components are created in the `evolution` folder, while standard components are stored in the `standard` folder. This helps us to better organize the components. 

Secondly, while building your component, utilizing Evolution-UI's development setup, you create its folder either in the evolution or standard folder. Ideally, it should work as a stand-alone component although it may make use of some components like grid, buttons etc as its dependencies. When you are satisfied with you component, you then add it to the showcase website.

**Comment by GabrieleRomeo** [comment]
Hi @PatrickFranz 

I merged your DROP Dot component with another PR so I close this PR

**Pull request closed without merging**
