### PR TITLE
Component - Text2Speech 

### PR DESCRIPTION
**Pull request by snagy22000**
@Gruximillian UPDATE TO PULL REQUEST:

* fixing major issue on firefox
* fixing issue css and html naming

* sync run of text2speech on firefox and chrome related to " npm module browser sync"

---------------------------------------

Merge conflicts fixed
* html fixed 
* css fixed
* js fixed

### CODE REVIEW

**Comment by Gruximillian** [comment]
@snagy22000 
Man, this looks really cool, but it doesn't work. Neither on Firefox nor Chrome. I'm on linux, maybe that's the reason. Also you have some styling issues, the text goes out of the bottom of the side panel.
And incredibly, closing and opening the side panel works simultaneously in Firefox and Chrome, I mean, when I click those buttons in one browser, it react in the other browser too, I never encuntered that kind of behavior.
Maybe @GabrieleRomeo can check this also, maybe the Web Speech API on linux doesn't work.

I'll leave this open, and iwhen you make updates, just push to your feature branch and the pull request will get updated. Then let me know to review it again.

Also, take care about the indentation, make it the same everywhere. And use css class naming convention more, you use it sparingly.

**Comment by snagy22000** [comment]
@Gruximillian Thanks for your feedback. Hmm I have to look if I can setup up a Linux machine for testing. On my Windows Machine everything is working fine. I will recheck everything and let you know. 
By the way if you want to test sites on different browser check this out: https://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots/ 
its Browserstack free from Microsoft

**Comment by snagy22000** [comment]
@Gruximillian I found the issue, it seems an old version of my CSS has been published from my local branch. That's why the CSS are not correctly named, I see also the issue which you had mentioned. I will take a further look why the old branch was published. I will keep you up to date.

**Comment by Gruximillian** [comment]
@snagy22000 
> By the way if you want to test sites on different browser check this out: https://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots/
its Browserstack free from Microsoft

Thanks for this and for making changes. I will review your code in a while.

**Comment by Gruximillian** [comment]
@snagy22000 

Damn, I can't seem to make it speak. 😄 
Other issues are fixed. I made a new pull request for this component, and asked others who work on this framework to test it. So we'll see after that what we'll do. I will close this pull request now.

**Comment by snagy22000** [comment]
@Gruximillian  Please let me know if the component get merged I tested it on OSX and it works. I have now to work on other tasks. Thanks in advance.

**Pull request closed without merging**
