### PR TITLE
T2s

### PR DESCRIPTION
**Pull request by Gruximillian**
@GabrieleRomeo @cbracco @escorponox @jmatembu @snagy22000 

Guys, please check this component, it's text2speech from Segastian Nagy. I just can't get it to speak. Maybe it's because of my system. I don't know.

### CODE REVIEW

**Comment by GabrieleRomeo** [comment]
@Gruximillian @cbracco @escorponox 

On my Mac works properly. Just a tip for @snagy22000 

When I use the `SHIFT + ` combination, buttons do not provide a visual feedback to the user (if the box is still opened, of course).

In my opinion, if the intended button gets the pressed status (when necessary), It would be even better.

**Comment by snagy22000** [comment]
Thanks for the hint. I have still some improvements on my agenda but for the time being, i will leave the first release as it is. If there are no technical issue, please let me know when it will be merged. thx sebastian

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by escorponox** [comment]
@snagy22000 

This function is throwing errors in the showcase because there is no `this.chbxReadController`

```js
toggleSpeechController: function (e) {
      if (this.chbxReadController.checked === false) {
        // console.log(e.target);
        document.querySelector('.evo_c-text2speech__controller ').style.transform = 'translateX(-5.4rem)';
      } else if (this.chbxReadController.checked === true) {
        // console.log(e.target);
        document.querySelector('.evo_c-text2speech__controller ').style.transform = 'translateX(-23.6rem)';
      }
    },
```

**Comment by snagy22000** [comment]
@escorponox  Hi Carlos, tested against my code and I didn´t have the same error like you. Please see the screenshot. 
screenshot-2017-04-07

It runs through the If Statement without any error. I ´m not sure why you got this error.

**Comment by escorponox** [comment]
@snagy22000 

The error is thrown in the showcase site

**Comment by GabrieleRomeo** [comment]
@snagy22000 

Yep. The problem is in every other component.. 

You can easily solve it in this way:

```
toggleSpeechController: function (e) {

      // When the checkbox is null, do nothing
      if (!this.chbxReadController) {
        return;
      }

      if (this.chbxReadController.checked === false) {
        // console.log(e.target);
        document.querySelector('.evo_c-text2speech__controller ').style.transform = 'translateX(-5.4rem)';
      } else if (this.chbxReadController.checked === true) {
        // console.log(e.target);
        document.querySelector('.evo_c-text2speech__controller ').style.transform = 'translateX(-23.6rem)';
      }
    },
```

**Pull request merged**
