### PR TITLE
popover - add to showcase

### PR DESCRIPTION
**Pull request by hiepvo**

### CODE REVIEW

**Comment by jmatembu** [comment]
Hey @hiepvo 

Nice work with this innovative component. Just two issues:
* When I click the label that activates the pop over, I am unable to hide/deactivate the pop over. Wouldn't it be great that I can click away to hide/deactivate the popover to continue reading the rest of the text?
* Drop the inline styles on the component wrapper element. I fixed that in your previous PR but thought I should let you know. We will be adding proper spacing to the website for the components.

**Comment by hiepvo** [comment]
hi @jmatembu ,

- When I click the label that activates the pop over, I am unable to hide/deactivate the pop over. Wouldn't it be great that I can click away to hide/deactivate the popover to continue reading the rest of the text?
--> Do you see close button at top-right of the popover? I think I added image to the framework. Let me know if you didnot see it. For "click away" do you mean that we click out side popover? Currently, the popover doesnot support it. We need to click to the close icon to close it or click to another popover.
- Drop the inline styles on the component wrapper element. I fixed that in your previous PR but thought I should let you know. We will be adding proper spacing to the website for the components.
--> Thank you.

**Comment by jmatembu** [comment]
No, I don't see the close button. That's the reason I asked that I should be able to click away to close the popover. Let's have that close button.

**Comment by hiepvo** [comment]
hi @jmatembu, the latest PR has made some changes on path. Can you merge it and double check again?

**Comment by jmatembu** [comment]
Okay @hiepvo, I will check this. Thank you for making the changes.

**Pull request merged**
